### ISSUE TITLE
Problem with pc file that requires package using full path

### ISSUE THREAD

**Issue by jhuckabee** [ruby-gnome/pkg-config#18]
I'm not sure if this is actually a problem with Homebrew or the `pkg-config` ruby gem, but I'm going to start here.

When trying to install the `gobject-introspection` gem, I get the following error while building the native extensions:

```
Building native extensions. This could take a while...
ERROR:  Error installing gobject-introspection:
	ERROR: Failed to build gem native extension.

    current directory: /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/gobject-introspection-3.3.8/ext/gobject-introspection
/Users/mattdegoey/.rbenv/versions/2.5.5/bin/ruby -r ./siteconf20190926-61306-3s06c8.rb extconf.rb
checking for --enable-debug-build option... no
checking for -Wall option to compiler... yes
checking for -Waggregate-return option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... yes
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
checking for -Wpointer-arith option to compiler... yes
checking for -Wswitch-default option to compiler... yes
checking for -Wswitch-enum option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wout-of-line-declaration option to compiler... yes
checking for -Wunsafe-loop-optimizations option to compiler... no
checking for -Wwrite-strings option to compiler... yes
checking for Homebrew... yes
checking for gobject-introspection-1.0... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/mattdegoey/.rbenv/versions/2.5.5/bin/$(RUBY_BASE_NAME)
	--enable-debug-build
	--disable-debug-build
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.8/lib/pkg-config.rb:342:in `parse_pc': .pc for /usr/local/opt/libffi/lib/pkgconfig/libffi.pc doesn't exist. (RuntimeError)
	from /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.8/lib/pkg-config.rb:218:in `declaration'
	from /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.8/lib/pkg-config.rb:232:in `collect_cflags'
	from /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.8/lib/pkg-config.rb:167:in `cflags'
	from /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.8/lib/pkg-config.rb:234:in `block in collect_cflags'
	from /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.8/lib/pkg-config.rb:233:in `collect'
	from /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.8/lib/pkg-config.rb:233:in `collect_cflags'
	from /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.8/lib/pkg-config.rb:167:in `cflags'
	from /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.8/lib/pkg-config.rb:237:in `block in collect_cflags'
	from /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.8/lib/pkg-config.rb:236:in `collect'
	from /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.8/lib/pkg-config.rb:236:in `collect_cflags'
	from /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.8/lib/pkg-config.rb:176:in `cflags_only_other'
	from /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.8/lib/pkg-config.rb:519:in `cflags_only_other'
	from /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.8/lib/pkg-config.rb:566:in `have_package'
	from /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/glib2-3.3.8/lib/mkmf-gnome2.rb:450:in `required_pkg_config_package'
	from extconf.rb:51:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-18/2.5.0-static/gobject-introspection-3.3.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/gobject-introspection-3.3.8 for inspection.
Results logged to /Users/mattdegoey/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-18/2.5.0-static/gobject-introspection-3.3.8/gem_make.out
```

glib has been installed via homebrew. Upon further inspection, I find within the `/usr/local/Cellar/glib/2.62.0_1/lib/pkgconfig/gobject-2.0.pc` file the following:

```
prefix=/usr/local/Cellar/glib/2.62.0_1
libdir=${prefix}/lib
includedir=${prefix}/include

Name: GObject
Description: GLib Type, Object, Parameter and Signal Library
Version: 2.62.0
Requires: glib-2.0
Requires.private: /usr/local/opt/libffi/lib/pkgconfig/libffi.pc >=  3.0.0
Libs: -L${libdir} -lgobject-2.0
Libs.private: -lintl
Cflags: -I${includedir}
```

That `Requires.private` line is what is causing issues. I'm not entirely sure if that's valid for a `.pc` file or not, but the `pkg-config` gem doesn't seem to handle cases where the required packages are listed as a path instead of it just being the package's name.
 
My setup:

```
Mac OS X 10.14.6
Ruby 2.5.5
Rbenv 1.1.2

Homebrew versions:
glib 2.62.0_1
libffi 3.2.1
gobject-introspection 1.62.0
```

**Comment by jhuckabee** [comment]
It looks like this was caused by a [change in the most recent glib Homebrew formula](https://github.com/Homebrew/homebrew-core/commit/51695fb3aad88ffb06a2d2a707b0b7814def5971#diff-dd6151159ff50afb2fa4c615a127e9df).

**Comment by kou** [comment]
Thanks for your report.
I've fixed this.

**Comment by andymeneely** [comment]
@kou to the rescue!! Thanks.

**Comment by jhuckabee** [comment]
Thanks for the quick fix!

**Comment by kou** [comment]
1.3.9 has been released.
