### ISSUE TITLE
RMagick install fails with a segfault in pkg-config on Ruby 3.3.0 in Docker on M1 MacBook Pro

### ISSUE THREAD

**Issue by andyjeffries** [ruby-gnome/pkg-config#24]
I raised this as an issue in RMagick's repo (https://github.com/rmagick/rmagick/issues/1450) but they said it may be better posted here.

### Description
When we try to build RMagick 5.3.0 or 5.4.1 on an M1 running Docker, we get an error (consistently using our app or a new Rails app, our Dockerfile based on alpine image, or Rails default using slim).

### Steps to Reproduce
1. Install Rails 7.1.3
2. Create a new app with `rails new test_app` and cd in to `test_app/`
3. Run `bundle add rmagick` to add it to the `Gemfile`
4. Edit the `Dockerfile` and add `imagemagick libmagickwand-dev` to line 22 (beginning with `apt-get install`)
5. Run `docker build .`

Build fails with:

```
#14 17.23 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
#14 17.23
#14 17.23 current directory:
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/rmagick-5.4.1/ext/RMagick
#14 17.23 /usr/local/bin/ruby extconf.rb
#14 17.23 checking for brew... no
#14 17.23 checking for pacman... no
#14 17.23 checking for Ruby version >= 2.3.0... yes
#14 17.23 checking for outdated ImageMagick version (<= 6.7.7)... no
#14 17.23 checking for gcc... yes
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:439: [BUG]
#14 17.23 Segmentation fault at 0x0067ffffb37006c0
#14 17.23 ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [aarch64-linux]
#14 17.23
#14 17.23 -- Control frame information -----------------------------------------------
#14 17.23 c:0012 p:---- s:0068 E:002060 CFUNC  :next
#14 17.23 c:0011 p:0005 s:0064 e:000063 BLOCK
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:439
#14 17.23 c:0010 p:0018 s:0060 e:000059 METHOD <internal:kernel>:187
#14 17.23 c:0009 p:0014 s:0055 e:000054 METHOD
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:438
#14 17.23 c:0008 p:0035 s:0048 e:000047 METHOD
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:403
#14 17.23 c:0007 p:0003 s:0039 e:000038 METHOD
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:297
#14 17.23 c:0006 p:0007 s:0033 e:000032 METHOD
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:603
#14 17.23 c:0005 p:0108 s:0028 e:000025 METHOD extconf.rb:111
#14 17.23 c:0004 p:0018 s:0016 e:000015 METHOD extconf.rb:53 [FINISH]
#14 17.23 c:0003 p:---- s:0012 e:000011 CFUNC  :new
#14 17.23 c:0002 p:0067 s:0008 E:000f60 EVAL   extconf.rb:449 [FINISH]
#14 17.23 c:0001 p:0000 s:0003 E:000520 DUMMY  [FINISH]
#14 17.23
#14 17.23 -- Ruby level backtrace information ----------------------------------------
#14 17.23 extconf.rb:449:in `<main>'
#14 17.23 extconf.rb:449:in `new'
#14 17.23 extconf.rb:53:in `initialize'
#14 17.23 extconf.rb:111:in `configure_compile_options'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:603:in
#14 17.23 `cflags'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:297:in
#14 17.23 `cflags'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:403:in
#14 17.23 `collect_cflags'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:438:in
#14 17.23 `normalize_cflags'
#14 17.23 <internal:kernel>:187:in `loop'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:439:in
#14 17.23 `block in normalize_cflags'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:439:in
#14 17.23 `next'
#14 17.23
#14 17.23 -- Threading information ---------------------------------------------------
#14 17.23 Total ractor count: 1
#14 17.23 Ruby thread count for this ractor: 1
#14 17.23
#14 17.23 -- Machine register context ------------------------------------------------
#14 17.23   x0: 0x0000aaaad68d0b50  x1: 0x0000aaaad70d0250  x2: 0x0000ffffff13d8a0
#14 17.23   x3: 0x0000ffff993fff60  x4: 0x0000ffff99400018  x5: 0x0000ffff99420000
#14 17.23   x6: 0x0000ffffb3c58b88  x7: 0x0000000000000000 x18: 0x0000ffff97dcf8b0
#14 17.23  x19: 0x0000000000000000 x20: 0x0000000000000000 x21: 0x0000000000000000
#14 17.23  x22: 0x0000000000000000 x23: 0x0000000000000000 x24: 0x0000000000000000
#14 17.23  x25: 0x0000000000000000 x26: 0x0000000000000000 x27: 0x0000000000000000
#14 17.23  x28: 0x0000000000000000 x29: 0x0000000000000000  sp: 0x0000ffff99400000
#14 17.23  fau: 0x0067ffffb37006c0
#14 17.23
#14 17.23 -- C level backtrace information -------------------------------------------
#14 17.23
#14 17.23 To see why this extension failed to compile, please check the mkmf.log which can
#14 17.23 be found here:
#14 17.23
#14 17.23 /usr/local/bundle/ruby/3.3.0/extensions/aarch64-linux/3.3.0/rmagick-5.4.1/mkmf.log
#14 17.23
#14 17.23 extconf failed, uncaught signal 11
#14 17.23
#14 17.23 Gem files will remain installed in
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/rmagick-5.4.1 for inspection.
#14 17.23 Results logged to
#14 17.23 /usr/local/bundle/ruby/3.3.0/extensions/aarch64-linux/3.3.0/rmagick-5.4.1/gem_make.out
#14 17.23
#14 17.23   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
#14 17.23   /usr/local/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:28:in `build'
#14 17.23   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
#14 17.23 /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in
#14 17.23 build_extensions'
#14 17.23   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
#14 17.23   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
#14 17.23   /usr/local/lib/ruby/3.3.0/rubygems/installer.rb:852:in `build_extensions'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/rubygems_gem_installer.rb:76:in
#14 17.23 `build_extensions'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/rubygems_gem_installer.rb:28:in
#14 17.23 `install'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/source/rubygems.rb:205:in
#14 17.23 `install'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/installer/gem_installer.rb:54:in
#14 17.23 `install'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/installer/gem_installer.rb:16:in
#14 17.23 `install_from_spec'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/installer/parallel_installer.rb:132:in
#14 17.23 `do_install'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/installer/parallel_installer.rb:123:in
#14 17.23 `block in worker_pool'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/worker.rb:62:in
#14 17.23 `apply_func'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/worker.rb:57:in
#14 17.23 `block in process_queue'
#14 17.23   <internal:kernel>:187:in `loop'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/worker.rb:54:in
#14 17.23 `process_queue'
#14 17.23 /usr/local/bundle/ruby/3.3.0/gems/bundler-2.5.5/lib/bundler/worker.rb:90:in
#14 17.23 `block (2 levels) in create_threads'
#14 17.23
#14 17.23 An error occurred while installing rmagick (5.4.1), and Bundler cannot continue.
#14 17.23
#14 17.23 In Gemfile:
#14 17.23   rmagick
------
executor failed running [/bin/sh -c bundle install &&     rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git &&     bundle exec bootsnap precompile --gemfile]: exit code: 5
```

### System Configuration

- ImageMagick version: 7.1.1.26-r0 (alpine)
- RMagick version: 5.3.0 or 5.4.1
- Ruby version: 3.3.0
- Environment (Operating system, version and so on): Docker on M1, running Slim or Alpine

**Comment by kou** [comment]
I think that this is a bug of Ruby 3.3.0.
Could you report this to https://bugs.ruby-lang.org/ ?

FYI: I could reproduce this by the following command lines:

```console
$ docker run -it --platform=linux/arm64 registry.docker.com/library/ruby:3.3-slim bash
root@163711a82570:/# apt-get update
root@163711a82570:/# apt-get install --no-install-recommends -y build-essential pkg-config libmagickwand-dev
root@163711a82570:/# gem install rmagick
```

**Comment by andyjeffries** [comment]
Thanks, created as https://bugs.ruby-lang.org/issues/20264
